-- Solo deshabilitar RLS para que funcionen las APIs
ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE prestamos DISABLE ROW LEVEL SECURITY;
ALTER TABLE pagos DISABLE ROW LEVEL SECURITY;
ALTER TABLE solicitudes_prestamos DISABLE ROW LEVEL SECURITY;